export {default as Main} from "./Main"
export {default as NavBar} from "./NavBar"
export {default as Home} from "./Home"
export {default as Projects} from "./Projects"
export {default as About} from "./About"